packer {
  required_plugins {
    virtualbox = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/virtualbox"
    }
  }
}

variable "iso_url" {
  type        = string
  description = "URL to the ISO file"
  default     = "https://releases.ubuntu.com/jammy/ubuntu-22.04.5-live-server-amd64.iso"
}

variable "iso_checksum" {
  type        = string
  description = "Checksum of the ISO file"
  default     = "sha256:9bc6028870aef3f74f4e16b900008179e78b130e6b0b9a140635434a46aa98b0"
}

locals {
  vm_name = "ubuntu-vagrant-oreo"
}


source "virtualbox-iso" "autogenerated_1" {
  guest_os_type = "Ubuntu_64"
  vm_name       = local.vm_name

  iso_url       = var.iso_url
  iso_checksum  = var.iso_checksum

  communicator  = "ssh"
  ssh_username  = "oreo"
  ssh_private_key_file = #path to private key here
  ssh_timeout   = "5m"

  http_directory   = "http"
  shutdown_command = "echo 'oreo' | sudo -S shutdown -P now"

  disk_size = 20480
  headless  = false
  memory    = 2048
  cpus      = 2
  
   vboxmanage = [
    ["modifyvm", "{{.Name}}", "--nic1", "nat"]
  ]


  boot_wait = "30s"
  boot_command = [
    "<esc><wait><esc><wait>",
    "c<wait>",  
    "autoinstall ds=nocloud-net\\;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ---<enter><wait>",
    "initrd /casper/initrd<enter><wait>",
    "boot<enter>"
  ]
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]
  
  provisioner "shell" {
    inline = [
      "echo 'Provisioning started...'",
      "sudo apt-get update",
      "sudo apt-get install -y virtualbox-guest-utils virtualbox-guest-x11 virtualbox-guest-dkms",
      "echo 'Provisioning completed.'",
      "sudo apt install -y python3 python3-pip lynis git", 
      "wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg",
      "echo \"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main\" | sudo tee /etc/apt/sources.list.d/hashicorp.list",
      "sudo apt update && sudo apt install consul"
    ]
  }

  post-processor "vagrant" {
    output = "vagrant-ubuntu-{{timestamp}}.box"
  }
}